In [ ]:
import os
from sentence_transformers import SentenceTransformer
import requests
from transformers import __version__ as transformers_version
print(transformers_version)
import certifi

print(f"SSL_CERT_FILE: {os.environ['SSL_CERT_FILE']}") # The file where you need to add your proxy certificate if you are behind a corporate proxy like ZScale (like me)
print(f"certifi version: {certifi.__version__}")
print(f"certifi.where(): {certifi.where()}") # The certifi CA Bundle file, you can add your proxy certificate in this file if you are behind a corporate proxy like ZScale (like me)

print("Testing HTTPS...")
resp = requests.get("https://google.com", timeout=20)
print("Status:", resp.status_code)

print("Loading model...")
model = SentenceTransformer(model_name_or_path = "sentence-transformers/all-MiniLM-L6-v2")
print("Model loaded.")

5.9.0
SSL_CERT_FILE: C:\Users\yjaquier\.conda\envs\ollama\Library\ssl\cacert.pem
certifi version: 2026.05.20
certifi.where(): c:\Users\yjaquier\.conda\envs\ollama\Lib\site-packages\certifi\cacert.pem
Testing HTTPS...
Status: 200
Loading model...


Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3115.25it/s]


Model loaded.


In [10]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]
embeddings = model.encode(sentences)
print(embeddings.shape)

similarities = model.similarity(embeddings, embeddings)
print(similarities)
print(embeddings[0])

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2852.08it/s]


(3, 384)
tensor([[1.0000, 0.6660, 0.1046],
        [0.6660, 1.0000, 0.1411],
        [0.1046, 0.1411, 1.0000]])
[ 1.91957522e-02  1.20085329e-01  1.59598291e-01  6.70659095e-02
  5.00748083e-02 -2.59187017e-02  5.64681962e-02 -9.28577334e-02
 -3.76114510e-02  6.32387493e-03 -4.28877473e-02  4.02834639e-03
  4.72777523e-03  3.24675962e-02  4.95197773e-02  5.29818274e-02
 -4.04454172e-02 -2.14836895e-02 -3.02760303e-02  2.20858455e-02
 -1.60775855e-01  8.08077976e-02 -2.80130561e-02  8.06255937e-02
 -2.85814330e-02  5.35818525e-02  1.26382308e-02  4.79190946e-02
  5.71111357e-03 -3.25831212e-02 -2.61571705e-02  8.00957531e-02
  1.47315878e-02 -3.24082486e-02 -4.12552394e-02 -9.68343113e-03
  5.00759401e-04 -1.56286821e-01 -6.77877367e-02  4.88779135e-02
  1.88976154e-02 -7.97722489e-02  2.43868306e-02  5.46689844e-03
  1.10656386e-02 -7.77949253e-03 -2.20388342e-02  3.50319929e-02
  1.06080189e-01 -4.72453795e-03 -5.78185171e-02  2.34565753e-02
 -5.92035577e-02 -6.09013177e-02 -7.7856823

In [13]:
from BM25 import chunks_from_markdown_files 
from sentence_transformers import SentenceTransformer

print("Loading model...")
model = SentenceTransformer(model_name_or_path = "sentence-transformers/all-MiniLM-L6-v2")

chunks = chunks_from_markdown_files()
# for i, chunk in enumerate(chunks):
#   # print(f"[{i+1}] ({len(chunk["chunk"])} chunks):")
#   # print(chunk[:80] + "..." if len(chunk) > 80 else chunk)
#   print(chunks[i])

print("Generating embeddings...")
# sentences = [chunk["chunk"] for chunk in chunks]
sentences = ["\n".join(x for x in [" > ".join(item.get("header_path", [])), item.get("chunk", "")] if x) for item in chunks]
embeddings = model.encode(inputs = sentences, show_progress_bar = False, convert_to_numpy = True)
# print(embeddings.shape)

print("Computing question similarities...")
query = "How to generate an AWR report in HTML format ?"
query_embedding = model.encode(inputs = [query], show_progress_bar = False, convert_to_numpy = True)
scores = model.similarity(query_embedding, embeddings)
# print(scores)
# if hasattr(scores, "detach"):  # torch tensor
#   scores = scores.detach().cpu().numpy()

sorted_scores, sorted_indices = scores.flatten().sort(descending = True)
print(sorted_scores)
print(sorted_indices)
top_k = 10
for rank, idx in enumerate(sorted_indices[:top_k], start=1):
  print(f"--------------------------------------------------------------------------------\nRank {rank:02d} (score: {scores.flatten()[idx]:.4f}), File: {chunks[idx]['source']}\nChunk: {chunks[idx]['chunk']}")


Loading model...


Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3222.37it/s]


Generating embeddings...
Computing question similarities...
tensor([ 0.7180,  0.6037,  0.5949,  ..., -0.1737, -0.1738, -0.1784])
tensor([2553, 2233, 3275,  ..., 1917,  838, 3458])
--------------------------------------------------------------------------------
Rank 01 (score: 0.7180), File: skills-main\db\performance\awr-reports.md
Chunk: ```sql
SELECT output
FROM   TABLE(
DBMS_WORKLOAD_REPOSITORY.AWR_REPORT_HTML(
l_dbid      => (SELECT dbid FROM v$database),
l_inst_num  => 1,
l_bid       => 200,
l_eid       => 201
)
);
```
--------------------------------------------------------------------------------
Rank 02 (score: 0.6037), File: skills-main\db\monitoring\top-sql-queries.md
Chunk: ```sql
-- Get the latest sql_exec_id for this SQL
SELECT sql_exec_id, sql_exec_start, elapsed_time/1e6 AS elapsed_sec, status
FROM   v$sql_monitor
WHERE  sql_id = 'abc123def456g'
ORDER BY sql_exec_start DESC
FETCH FIRST 1 ROW ONLY;
```  
Then generate the HTML report as shown above.  
---
----------------

In [ ]:
sorted_scores, sorted_indices = scores.flatten().sort(descending=True)

print(sorted_scores[:top_k])
print(sorted_indices[:top_k])

print(len(chunks))
print(len(sorted_scores))

idx = 3190
print(
  f"{'-'*80}\n"
  f"Index {idx} (score: {scores.flatten()[idx]:.4f}), "
  f"File: {chunks[idx]['source']}\n"
  f"Chunk: {chunks[idx]['chunk']}"
)

tensor([0.7180, 0.6037, 0.5949, 0.5728, 0.5585, 0.5424, 0.5158, 0.5157, 0.5102,
        0.4936])
tensor([2553, 2233, 3275, 3272, 3273, 3276, 2552, 2554, 3278, 3572])
3578
3578
--------------------------------------------------------------------------------
Index 3190 (score: 0.0767), File: skills-main\db\sql-dev\sql-injection-avoidance.md
Chunk: ```plsql
-- DANGEROUS: an attacker can pass 'employees WHERE 1=1 UNION SELECT ...'
CREATE OR REPLACE PROCEDURE count_rows_unsafe (
p_table_name IN VARCHAR2
) AS
v_count NUMBER;
BEGIN
EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || p_table_name
INTO v_count;
DBMS_OUTPUT.PUT_LINE('Count: ' || v_count);
END;
/

-- SAFE: DBMS_ASSERT.SQL_OBJECT_NAME raises an error if the table doesn't exist
-- and rejects any string containing SQL syntax characters
CREATE OR REPLACE PROCEDURE count_rows_safe (
p_table_name IN VARCHAR2
) AS
v_count      NUMBER;
v_safe_name  VARCHAR2(128);
BEGIN
v_safe_name := DBMS_ASSERT.SQL_OBJECT_NAME(p_table_name);
EXECUTE IMMEDIATE

In [ ]:
scores = model.similarity(query_embedding, embeddings)
unsorted_with_doc_ids = [
  {"id": doc_id, "file": chunks[doc_id]["source"], "chunk": chunks[doc_id]["chunk"], "embedding_score": float(scores.flatten()[doc_id])}
  for doc_id in range(len(chunks))
]

# optional preview
print(unsorted_with_doc_ids[:10])

[{'id': 0, 'file': 'skills-main\\db\\admin\\backup-recovery.md', 'chunk': "Recovery Manager (RMAN) is Oracle's primary tool for database backup, restore, and recovery operations. It provides block-level backup integrity checking, compression, encryption, incremental backups, and tight integration with the Oracle database engine. RMAN eliminates the need for manual backup scripting and ensures consistent backups even for an open database.  \nUnderstanding backup and recovery is the single most critical skill for any Oracle DBA. A database that cannot be recovered is a database that cannot be trusted.  \n---", 'embedding_score': 0.08546111732721329}, {'id': 1, 'file': 'skills-main\\db\\admin\\backup-recovery.md', 'chunk': "**RMAN Executable**\nThe `rman` binary that connects to the target database and optionally a recovery catalog. It interprets RMAN commands, communicates with the target database server processes, and manages backup metadata.  \n**Target Database**\nThe database being b

In [5]:
import importlib
import BM25
importlib.reload(BM25)
import embeddings
importlib.reload(embeddings)
from BM25 import chunks_from_markdown_files
from embeddings import embedding_score, compute_embedding_from_chunks

chunks = chunks_from_markdown_files()
chunk_embeddings = compute_embedding_from_chunks(chunks)
query = "How to generate an AWR report in HTML format ?"
embedding_score_dict = embedding_score(query, chunk_embeddings, chunks)
# for item in sorted(embedding_score_dict, key=lambda x: x["embedding_score"], reverse=True)[:10]:
#   print(f"id: {item['id']}, source: {item['source']}, score: {item['embedding_score']:.4f}\n")
for i, rank in enumerate(
  sorted(embedding_score_dict, key=lambda x: x["embedding_score"], reverse=True)[:5],
  start=1
):
  print(
    f"{'-'*80}\n"
    f"Rank {i} (score: {rank['embedding_score']:.2f}), File: {rank['source']}\n"
    f"Chunk: {rank['chunk']}"
  )

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

--------------------------------------------------------------------------------
Rank 1 (score: 0.72), File: skills-main\db\performance\awr-reports.md
Chunk: ```sql
SELECT output
FROM   TABLE(
DBMS_WORKLOAD_REPOSITORY.AWR_REPORT_HTML(
l_dbid      => (SELECT dbid FROM v$database),
l_inst_num  => 1,
l_bid       => 200,
l_eid       => 201
)
);
```
--------------------------------------------------------------------------------
Rank 2 (score: 0.60), File: skills-main\db\monitoring\top-sql-queries.md
Chunk: ```sql
-- Get the latest sql_exec_id for this SQL
SELECT sql_exec_id, sql_exec_start, elapsed_time/1e6 AS elapsed_sec, status
FROM   v$sql_monitor
WHERE  sql_id = 'abc123def456g'
ORDER BY sql_exec_start DESC
FETCH FIRST 1 ROW ONLY;
```  
Then generate the HTML report as shown above.  
---
--------------------------------------------------------------------------------
Rank 3 (score: 0.59), File: skills-main\db\sqlcl\sqlcl-awr.md
Chunk: ```sql
-- No IDs needed — uses the most recent inter